# Generated by Django 5.2.4 on 2025-11-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_rating_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "image",
                    models.ImageField(upload_to="advertisements/", verbose_name="عکس"),
                ),
                ("link", models.URLField(blank=True, null=True, verbose_name="لینک")),
                (
                    "position",
                    models.CharField(
                        choices=[("right", "سمت راست"), ("left", "سمت چپ")],
                        max_length=10,
                        verbose_name="موقعیت",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب نمایش")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "تبلیغ",
                "verbose_name_plural": "تبلیغات",
                "ordering": ["position", "order"],
            },
        ),
    ]
