# Generated by Django 5.2.4 on 2025-11-25 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_advertisement"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("tehran", "تهران"),
                            ("isfahan", "اصفهان"),
                            ("fars", "فارس"),
                            ("khorasan-razavi", "خراسان رضوی"),
                            ("azarbaijan-sharghi", "آذربایجان شرقی"),
                            ("mazandaran", "مازندران"),
                            ("khorasan-shomali", "خراسان شمالی"),
                            ("khorasan-jonubi", "خراسان جنوبی"),
                            ("alborz", "البرز"),
                            ("gilan", "گیلان"),
                            ("kerman", "کرمان"),
                            ("lorestan", "لرستان"),
                            ("azarbaijan-gharbi", "آذربایجان غربی"),
                            ("hamadan", "همدان"),
                            ("kermanshah", "کرمانشاه"),
                            ("yazd", "یزد"),
                            ("ardabil", "اردبیل"),
                            ("bushehr", "بوشهر"),
                            ("zanjan", "زنجان"),
                            ("semnan", "سمنان"),
                            ("qom", "قم"),
                            ("golestan", "گلستان"),
                            ("qazvin", "قزوین"),
                            ("markazi", "مرکزی"),
                            ("chaharmahal-bakhtiari", "چهارمحال و بختیاری"),
                            ("kohgiluyeh-boyer-ahmad", "کهگیلویه و بویراحمد"),
                            ("ilam", "ایلام"),
                            ("kordestan", "کردستان"),
                            ("hormozgan", "هرمزگان"),
                            ("sistan-baluchestan", "سیستان و بلوچستان"),
                            ("west-azarbaijan", "آذربایجان غربی"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="نام استان",
                    ),
                ),
            ],
            options={
                "verbose_name": "شهر",
                "verbose_name_plural": "شهرها",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="advertisement",
            options={
                "ordering": ["position", "order", "-created_at"],
                "verbose_name": "تبلیغ",
                "verbose_name_plural": "تبلیغات",
            },
        ),
        migrations.AddField(
            model_name="advertisement",
            name="ad_type",
            field=models.CharField(
                choices=[("image", "عکس"), ("gif", "گیف"), ("video", "ویدیو")],
                default="image",
                max_length=10,
                verbose_name="نوع تبلیغ",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="gif_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="advertisements/gifs/",
                verbose_name="فایل گیف",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="advertisements/videos/",
                verbose_name="فایل ویدیو",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="video_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="لینک ویدیو (اختیاری)"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="meal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("breakfast", "صبحانه"),
                    ("lunch", "ناهار"),
                    ("dinner", "شام"),
                    ("snack", "میان\u200cوعده"),
                    ("all", "همه"),
                ],
                max_length=20,
                null=True,
                verbose_name="نوع وعده",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="price_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cheap", "ارزان"),
                    ("moderate", "متوسط"),
                    ("expensive", "گران"),
                    ("very-expensive", "خیلی گران"),
                ],
                max_length=20,
                null=True,
                verbose_name="محدوده قیمت",
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="advertisements/", verbose_name="عکس"
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="لینک (اختیاری)"),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="position",
            field=models.CharField(
                choices=[("left", "سمت چپ"), ("right", "سمت راست")],
                max_length=10,
                verbose_name="موقعیت",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="restaurants",
                to="restaurants.city",
                verbose_name="شهر",
            ),
        ),
    ]
