# Generated by Django 5.2.4 on 2025-11-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_city_alter_advertisement_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("breakfast", "صبحانه"),
                            ("lunch", "ناهار"),
                            ("dinner", "شام"),
                            ("snack", "میان\u200cوعده"),
                            ("all", "همه"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="نوع وعده",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع وعده",
                "verbose_name_plural": "انواع وعده",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="meal_type",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="price_range",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="meal_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="restaurants",
                to="restaurants.mealtype",
                verbose_name="انواع وعده",
            ),
        ),
    ]
