# Generated by Django 5.2.4 on 2025-11-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0005_mealtype_remove_restaurant_meal_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("gym", "باشگاه"),
                            ("restaurant", "رستوران"),
                            ("trainer", "مربیان"),
                            ("doctor", "پزشکان"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="نام دسته",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="آیکون"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب نمایش")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
                "ordering": ["order", "name"],
            },
        ),
    ]
