# Generated by Django 5.2.4 on 2025-11-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0006_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="section",
            field=models.CharField(
                choices=[("gym", "باشگاه"), ("restaurant", "رستوران")],
                default="gym",
                max_length=20,
                verbose_name="بخش",
            ),
        ),
    ]
