# Generated by Django 5.2.4 on 2025-11-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0007_advertisement_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="section",
            field=models.CharField(
                choices=[
                    ("gym", "باشگاه"),
                    ("restaurant", "رستوران"),
                    ("trainer", "مربیان"),
                ],
                default="gym",
                max_length=20,
                verbose_name="بخش",
            ),
        ),
    ]
