# Generated by Django 5.2.4 on 2025-11-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0006_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام باشگاه")),
                ("address", models.TextField(verbose_name="آدرس")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gyms",
                        to="restaurants.city",
                        verbose_name="شهر",
                    ),
                ),
            ],
            options={
                "verbose_name": "باشگاه",
                "verbose_name_plural": "باشگاه\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GymImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gyms/", verbose_name="عکس")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="توضیحات"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="gym.gym",
                        verbose_name="باشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "عکس باشگاه",
                "verbose_name_plural": "عکس\u200cهای باشگاه",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GymPhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="شماره تلفن")),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="gym.gym",
                        verbose_name="باشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "شماره تلفن",
                "verbose_name_plural": "شماره\u200cهای تلفن",
            },
        ),
        migrations.CreateModel(
            name="GymRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 ستاره"),
                            (2, "2 ستاره"),
                            (3, "3 ستاره"),
                            (4, "4 ستاره"),
                            (5, "5 ستاره"),
                        ],
                        verbose_name="امتیاز",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="gym.gym",
                        verbose_name="باشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "امتیاز",
                "verbose_name_plural": "امتیازها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GymComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="ایمیل"
                    ),
                ),
                ("comment", models.TextField(verbose_name="نظر")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="تایید شده"),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="gym.gym",
                        verbose_name="باشگاه",
                    ),
                ),
                (
                    "rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comment",
                        to="gym.gymrating",
                        verbose_name="امتیاز مرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر",
                "verbose_name_plural": "نظرات",
                "ordering": ["-created_at"],
            },
        ),
    ]
