# Generated by Django 5.2.4 on 2025-11-26 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("pool", "استخر"),
                            ("sauna", "سونا"),
                            ("jacuzzi", "جکوزی"),
                            ("parking", "پارکینگ"),
                            ("cafe", "کافه"),
                            ("locker_room", "رختکن"),
                            ("other", "سایر موارد"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="امکانات",
                    ),
                ),
            ],
            options={
                "verbose_name": "امکانات",
                "verbose_name_plural": "امکانات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PriceRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("low", "اقتصادی"),
                            ("medium", "متوسط"),
                            ("high", "گران"),
                            ("premium", "لوکس"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="محدوده قیمت",
                    ),
                ),
            ],
            options={
                "verbose_name": "محدوده قیمت",
                "verbose_name_plural": "محدوده\u200cهای قیمت",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SportType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("bodybuilding", "بدنسازی"),
                            ("horse_riding", "سوارکاری"),
                            ("swimming", "شنا"),
                            ("football", "فوتبال"),
                            ("volleyball", "والیبال"),
                            ("yoga", "یوگا"),
                            ("crossfit", "کراس فیت"),
                            ("pilates", "پیلاتس"),
                            ("handball", "هندبال"),
                            ("other", "سایر موارد"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="نوع ورزش",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع ورزش",
                "verbose_name_plural": "انواع ورزش",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="gym",
            name="facilities",
            field=models.ManyToManyField(
                blank=True,
                related_name="gyms",
                to="gym.facility",
                verbose_name="امکانات",
            ),
        ),
        migrations.AddField(
            model_name="gym",
            name="price_range",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gyms",
                to="gym.pricerange",
                verbose_name="محدوده قیمت",
            ),
        ),
        migrations.AddField(
            model_name="gym",
            name="sport_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="gyms",
                to="gym.sporttype",
                verbose_name="نوع ورزش",
            ),
        ),
    ]
